const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const path = require("node:path");
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(__dirname, "../Model.js"), "utf8").replace(/^\.pragma library\s*/, ""), ctx);
const now = 100000;
const active = { updated: 100, healthy: true, mode: "sealed", phase: "active" };
assert.equal(ctx.visualState(active, now, false), "sealed");
assert.equal(ctx.visualState({...active, mode: "manual-wifi"}, now, false), "manual-wifi");
assert.equal(ctx.visualState({...active, updated: 80}, now, false), "error");
assert.equal(ctx.visualState({...active, healthy: false}, now, false), "error");
assert.equal(ctx.visualState({...active, mode: "off", updated: 80}, now, false), "error");
assert.equal(ctx.visualState({...active, phase: "restoring"}, now, false), "error");
assert.equal(ctx.title("error", "restoring"), "Restore incomplete");
assert.equal(ctx.visualState(active, now, true), "applying");
const restoring = {...active, phase: "restoring", healthy: false, working: true, operation: "restoring"};
assert.equal(ctx.visualState(restoring, now, false), "applying");
assert.equal(ctx.title("applying", "restoring", "restoring"), "Restoring…");
assert.equal(ctx.title("applying", "off", "restoring"), "Restoring…");
assert.equal(ctx.visualState({...restoring, updated: 80}, now, false), "error");
assert.equal(ctx.visualState({...restoring, working: false}, now, false), "error");
assert.equal(ctx.inProgress(restoring, now, false), true);
assert.equal(ctx.inProgress({...restoring, updated: 80}, now, false), false);
assert.equal(ctx.visualState({...active, phase: "applying", updated: 80}, now, false), "error");
console.log("PASS: UI health, stale status, restoring, and mode states");
